apiVersion: v1
kind: Service
metadata:
  name: product-ms-svc
  namespace: bootcamp
spec:
  selector:
    app: product-ms
  ports:
    - protocol: TCP
      name: http
      port: 8080
      targetPort: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-ms-deploy
  namespace: bootcamp
  labels:
    app: product-ms
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product-ms
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: product-ms
      annotations:
        sidecar.isitio.io/inject: "false"
    spec:
      containers:
        - name: product-ms
          image: nikhilperennial/productms:1.0.0.4
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
          resources:
            limits:
              memory: 1.5Gi
              cpu: 200m
            requests:
              memory: 100Mi
              cpu: 10m